# Funding sources for ArcaP — Open Data Platform
# Built and maintained by Mustapha Fonsau @ Talentys
# https://talentys.eu | https://www.linkedin.com/company/talentysdata

github: [Monsau]
# patreon: talentys
# open_collective: arcap
custom:
  - https://talentys.eu
  - https://www.linkedin.com/company/talentysdata
