apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arcap

resources:
  - namespace.yaml
  - ai/qdrant-deployment.yaml
  - ai/ollama-deployment.yaml
  - ai/embedding-service-deployment.yaml
  - ai/rag-api-deployment.yaml
  - ai/chat-ui-deployment.yaml
  - ai/minio-ai-deployment.yaml
  - openmetadata/openmetadata-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: arcap
  app.kubernetes.io/managed-by: kustomize
